### ISSUE TITLE
A strange bug/error (frame index mismatch) in the `experiment_realtime.m`?

### ISSUE THREAD

**Issue by huanglianghua** [votchallenge/toolkit-legacy#178]
Hi, Luca,

The code in in file `experiment_realtime.m` is somewhat obscure for me to understand, and it seems to me that there are some errors?

For example, the following lines of code:

```
data.offset = 0;
...
previous = data.index;
current = round(floor(data.time * data.fps) / 1000) + data.offset;
```

For the 2nd, 3rd and 4th frames, the values of `current` are `1, 2, 3` instead of `2, 3, 4`.

So is there a serious mismatch between the `current` and the real indices of current frames?

Also, I have compared the results in `vot2017_results`, specifically results of the sequence `ants1` of tracker `CCOT`. The comparison of the files `ants_001.txt` and `ants1_time.txt` shows that the index of corresponding results seem not match.

**Comment by lukacu** [comment]
Hi, sorry for replying so late, I was busy with other things for some time. I think we have looked at this at the time and found no problem, but I will check it again, just in case.
