### ISSUE TITLE
matlab has encountered an internall problem and needs to close

### ISSUE THREAD

**Issue by haoliyoupai09** [votchallenge/toolkit-legacy#192]
VOT version: 2016
Matlab: 2014b and 2016a
problem description:
I incorporate my tracker to the VOT2016 toolkit and obtain the baseline and unsupervised results through run_experiment.m. Then I try to compare the performance with other trackers, however, every time I put my tracker name in the tracker_list in run_analysis.m, the matlab crashes during the running process (Matlab has encountered an internal problem and needs to close). After I replace our tracker with other downloaded trackers in the track_list in run_analysis.m, it works well and generate the reports. I also change the matlab version from 2016a to 2014b, but the problem persisits. 
Could anyone know the reason and kindly tell me?
Any help is appreciated.

**Comment by lukacu** [comment]
This is strange, but you will have to provide more information for us to help us. Where in the analysis process did you observe the crash? Generally it is possible that the results are not complete, but this should not result in crash, only an exception.

**Comment by jonathantompson** [comment]
I am also seeing a similar issue for Matlab R2017b. During AR analysis the Matlab crash dump reports:

Abnormal termination:
Floating point exception

This is raised during execution of calculate_accuracy_overlap (line 190 of analyze_accuracy_robustness.m) called from trackers_raw_scores_selector, although I've seen it as a result of many other functions as well that call the C++ overlap method. Actually, I estimate that there's ~25% chance that the analysis code will run on a given results directory. It's seems quite unstable.

**Comment by lukacu** [comment]
This is a strange one, do you have some result files that I can check it with?

**Comment by jonathantompson** [comment]
The results files for 'DRT', 'FSAN' from the VOT website trigger the stack dump on our systems. The following tracker results definitely do not (there might be more but I haven't tried them all):

'ALAL', 'C3DT', 'CPT', 'CPT_fast', 'DeepSTRCF1', 'DLSTpp', 'ECO', 'FSAN', 'LADCF', 'LSART', 'SA_Siam_P', 'SA_Siam_R', 'SiamFC', 'SiamRPN'

**Comment by lukacu** [comment]
Thanks, I will have a look, but right now our priority is on running the experiments, we will check the analysis code a bit later.
