### ISSUE TITLE
Tracker has not passed the TraX support test.

### ISSUE THREAD

**Issue by ihpdep** [votchallenge/toolkit-legacy#198]
I have my code working on MacOS but cannot pass TraX support test on Ubuntu 16 and 18 (crashed on Matlab 2018). I am wondering maybe we can add a default Matlab tracker (e.g. NCC) in the default workspace when we create one. As the Matlab code is hard to debug, it can give hint about whether it is a tracker code problem or an environmental problem and can save a lot of time.

**Comment by 41xu** [comment]
I met the same problems as yours. Did you solve the problems? How you did?

**Comment by ihpdep** [comment]
@41xu Not yet. Just waiting for someone can solve the problem.

**Comment by lukacu** [comment]
Matlab 2018 did change some things so the cause may have been #185. Other than that you have to look in the log file for clues. If there is a timeout mentioned this means that you have to increase it, but it may also be something else.
