### ISSUE TITLE
conduction1 bbox from VOT uses REGION_LEGACY_RASTERIZATION 

### ISSUE THREAD

**Issue by jonathantompson** [votchallenge/toolkit-legacy#213]
The first frame BBox sent via trax for conduction1 (and other sequences with 'rectangle' region types) is rasterized to a polygon using REGION_LEGACY_RASTERIZATION == FALSE. This results in a bbox that is off by size 1 in each dimension.

In detail... It looks like the trax region for this sequence is going through this branch:

https://github.com/votchallenge/trax/blob/master/src/region.c#L400

when using the VOT python interface:

https://github.com/votchallenge/vot-toolkit/blob/master/tracker/examples/python/vot.py#L82 with region_format set to 'polygon'.  The GT region looks like it is handled correctly on the VOT side and this is confirmed by looking at the run_test.m output and seeing that the two bounding boxes rendered are off by one pixel.

the first line of conduction1/groundtruth.txt is:

`712.0,231.0,22.0,24.0`

Which it looks like I should interpret as xmin, ymin, width, height. Therefore, I EXPECT to receive the polygon:

`
[[xmin, ymin], [xmin + width, ymin], [xmin + width, ymin + height], [xmin, ymin + height]] =
  [[712.0, 231.0], [734.0, 231.0], [734.0, 255.0], [712.0, 255.0]]`

however I actually get (from trax):

`[[712.0, 231.0], [733.0, 231.0], [733.0, 254.0], [712.0, 254.0]]`

Inserting a few printf statements in region.c I am confirming that the REGION_LEGACY_RASTERIZATION flag is not set. Is this a bug? It looks like the target frame has inconsistent handling during overlap calculation on the GT region and when being sent over trax.

**Comment by lukacu** [comment]
I will have a look, it certainly looks strange. We have spent a lot of time with this overlap stuff a few years ago, but then it was mostly left as it. It is interesting that these problems appear only now, but I guess there are simply more people looking at the code.

**Comment by jonathantompson** [comment]
Thanks. Let me know if you need further clarification or help.
