### ISSUE TITLE
Tracker has not passed the TraX support test.

### ISSUE THREAD

**Issue by GitHubZhangpy** [votchallenge/toolkit-legacy#216]
when I use VOT with trax, I always catch the error:"Tracker has not passed the TraX support test." There is nothing in log and runtime.log. And I set global variable "trax_debug" to true. The log says as follow:

CLIENT: Working directory is /tmp/tpa919b1ce_a72f_4c51_a2a0_c6208aa4a477
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection

                            < M A T L A B (R) >
                  Copyright 1984-2017 The MathWorks, Inc.
                   R2017b (9.3.0.713579) 64-bit (glnxa64)
                             September 14, 2017

 
CLIENT: Unable to establish connection.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
CLIENT: Trying to terminate process nicely.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
I setup the latest vot and trax toolkit with the guidance of document. I wonder what is wrong with it. Thanks for your help.

**Comment by lukacu** [comment]
On Linux you can try running the tracker command manually in the terminal and see what the input is there, then paste it here.

**Comment by GitHubZhangpy** [comment]
Thanks for your reply. The tracker command is shown as follow:

/usr/local/MATLAB/R2017b/bin/matlab -nodesktop -nosplash -r "try; diary 'runtime.log'; addpath('/home/zpy/Desktop/vot-toolkit-master/trackers/TSCF/TSCF_sc/implementation/');addpath('/home/zpy/Desktop/vot-toolkit-master/native/mex');TSCF; catch ex; disp(getReport(ex)); end; quit;"

I think the command may be correct. And the terminal outputs and stucks at:
@@TRAX:hello "trax.image=path;" "trax.region=rectangle;" "trax.version=2" "trax.channels=color;"

**Comment by GitHubZhangpy** [comment]
The same problem occurs when I test ncc tracker. And I changed another PC and still has the same problems. I did not know what is wrong with it.

**Comment by Hackerlil** [comment]
I also confused with it,in ubuntu 16.04 ,matlab2017a...and show no logs

**Comment by ZekuiQin** [comment]
When i tested ncc tracker, error "Tracker execution interrupted: Unable to establish connection" happened. My PC system is macOS Mojave 10.14.4, compilers are Xcode with Clang and Xcode Clang++, i run the ncc tracker in matlab2017b. 

Then ncc tracker report error when it run to tracker_run.m(77) 
"data = traxclient(tracker.command, callback, ...
        'Directory', directory, 'Timeout', timeout, ...
        'Environment', environment, 'Connection', connection, ...
        'Data', data, mexargs{:});"
Please help!

**Comment by KMSZJJ** [comment]
@Hackerlil Have you solved it ? I have the same problem with you.

**Comment by tlok666** [comment]
ubuntu16.04, Matlab2018b,
When I try the Matlab ncc, everything is ok.
But when I try the Python ncc, it said,

Tracker has not passed the TraX support test

**Comment by tlok666** [comment]
tracker = tracker_load('ncc');
Initializing workspace ...
Verifying native components ...
Testing TraX protocol support for tracker ncc.
Tracker execution interrupted: Unable to establish connection.
TraX support not detected.
Error using tracker_load (line 127)
Tracker has not passed the TraX support test.

**Comment by GitHubZhangpy** [comment]
@ Hackerlil I have solved it by changing another version of MATLAB e.g. MATLAB 2015b. The reason is still unknown...

**Comment by tlok666** [comment]
> @ Hackerlil I have solved it by changing another version of MATLAB e.g. MATLAB 2015b. The reason is still unknown...

Thanks. I solved this problem.
At the first, I also changed another version to MATLAB2015b, but it does not work either on my computer.
So, I changed back to MATLAB2018b:
1. Download the Trax from github, cmake . , make, make install, and add it to system path. Until I can import trax in python console
2. Change the MATLAB pyversion. to the version that I use cv2 and pytorch(I use source activate pyXX to handle the envirment)
Finally, it works!

**Comment by SkyeSong38** [comment]
> > @ Hackerlil I have solved it by changing another version of MATLAB e.g. MATLAB 2015b. The reason is still unknown...
> 
> Thanks. I solved this problem.
> At the first, I also changed another version to MATLAB2015b, but it does not work either on my computer.
> So, I changed back to MATLAB2018b:
> 
> 1. Download the Trax from github, cmake . , make, make install, and add it to system path. Until I can import trax in python console
> 2. Change the MATLAB pyversion. to the version that I use cv2 and pytorch(I use source activate pyXX to handle the envirment)
>    Finally, it works!

I meet the same problem as yours. But I cannot import trax in python console. Can you tell me how to deal with it?
1. Download the Trax from GitHub
2. mkdir build 
3. cd build
4. cmake -DBUILD_PYTHON=ON ..
5. make
6 make install
when I tried step6, it said "error: package directory 'trax' does not exist"

**Comment by Hevans123** [comment]
I can import trax in python console. But I still meet above problem. Anyone have detailed solution?

**Comment by han3889847** [comment]
> > @ Hackerlil我已经通过更改另一个版本的MATLAB（例如MATLAB 2015b）解决了该问题。原因仍然未知...
> 
> 谢谢。我解决了这个问题。
> 最初，我还将另一个版本更改为MATLAB2015b，但它在我的计算机上也不起作用。
> 所以，我改回了MATLAB2018b：
> 
> 1. 从github，cmake下载Trax。，进行安装，然后将其添加到系统路径。直到我可以在python控制台中导入trax
> 2. 更改MATLAB pyversion。到我使用cv2和pytorch的版本（我使用源代码激活pyXX来处理环境）
>    最后，它起作用了！

Thanks for your comment!   I have completed step one, but I don't know how to complete the second step you said. Can you describe it in detail? It is best to have a screenshot. Thank you and may you success.

**Comment by laisimiao** [comment]
I also have this problem when I ran `run_experiments.m` using ncc tracker:
```@@TRAX:frame "file:///home/lsm/vot-toolkit-master/sequences/motocross/00000017.jpg" 

image =

    '/home/lsm/vot-toolkit-master/sequences/motocross/00000017.jpg'

@@TRAX:state "18.0000,60.0000,149.0000,146.0000" "confidence=0.668339" 
@@TRAX:frame "file:///home/lsm/vot-toolkit-master/sequences/motocross/00000018.jpg" 

image =

    '/home/lsm/vot-toolkit-master/sequences/motocross/00000018.jpg'

@@TRAX:state "24.0000,62.0000,149.0000,146.0000" "confidence=0.667992" 
CLIENT: Resetting program.
CLIENT: Trying to stop process using protocol.
@@TRAX:quit "trax.reason=" 
CLIENT: Trying to terminate process nicely.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Deleted stale client
CLIENT: Creating process /usr/local/MATLAB/R2017a/bin/matlab -nodesktop -nosplash -r "try; diary 'runtime.log'; addpath('/home/lsm/vot-toolkit-master/tracker/examples/matlab/');addpath('/home/lsm/vot-toolkit-master/native/mex');ncc; catch ex; disp(getReport(ex)); end; quit;"
CLIENT: Working directory is /tmp/tpae4924af_b161_470e_8920_198e507b93b5
CLIENT: Flushing streams
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Unable to establish connection.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
CLIENT: Trying to stop process using protocol.
      Tracker execution interrupted: Unable to establish connection.
Error using traxclient
Unable to establish connection.
```
**It seems that it's connection problem between client and server becaue of chinese wall**

**Comment by laisimiao** [comment]
But it always stop at 18.jpg

**Comment by XDUSPONGE** [comment]
> But it always stop at 18.jpg

hello have you solved the problem

**Comment by XDUSPONGE** [comment]
I have passed the ncc test. However for my own tracker, it sames strange that my tracker can only run on part of the vot dataset. For the ball1 ball2, blanket and so on  it can go through well, however, for other sequences, such as the bag, it can not run, which shows did not receive response, and nothing shown in the log file. And the environment is 
Matlab2016b cuda10.1 GTX TiTAN X
I hope you can provide some advice

**Comment by XDUSPONGE** [comment]
> Thanks for your reply. The tracker command is shown as follow:
> 
> /usr/local/MATLAB/R2017b/bin/matlab -nodesktop -nosplash -r "try; diary 'runtime.log'; addpath('/home/zpy/Desktop/vot-toolkit-master/trackers/TSCF/TSCF_sc/implementation/');addpath('/home/zpy/Desktop/vot-toolkit-master/native/mex');TSCF; catch ex; disp(getReport(ex)); end; quit;"
> 
> I think the command may be correct. And the terminal outputs and stucks at:
> @@Trax:hello "trax.image=path;" "trax.region=rectangle;" "trax.version=2" "trax.channels=color;"

sorry to bother you, may be the current version of vot toolkit can not satisfy my tracker, so could you please offer your successful vot-toolkit and trax for me, and you can send it to 1425722558@qq.com thanks very much
