### ISSUE TITLE
RGBT-vot2019

### ISSUE THREAD

**Issue by Alexadlu** [votchallenge/toolkit-legacy#225]
Hello, I am having such a problem. When I run the RGBT run_experiments file, the previous sequences can be executed normally. However, there will be an error in the subsequent sequence, so I will take these sequences to the run_test file and find that they can be executed normally. So I suspect that the problem may be in the test. For frames that fail to track the judgment, the vot-toolkit may have some mechanism that I don't understand that causes the error. I hope you can help me find some solutions.

error:

run_experiments
Initializing workspace ...
Verifying native components ...
Experiment baseline
  Tracker MANet
    Sequence afterrain
    Sequence aftertree
    Sequence baby
    Sequence baginhand
    Sequence baketballwaliking
      Repetition 1
CLIENT: Creating process /usr/bin/python2  -c "import sys; sys.path.append('/home/adlu/vot-toolkit-master/tracker/examples/python');sys.path.append('/home/adlu/vot-toolkit-master/native/trax/support/python'); import python_MANet"
CLIENT: Working directory is /tmp/tp96600421_baeb_4c41_90de_20d79570e9d3
CLIENT: Starting process
CLIENT: Setting up TraX with standard streams connection
@@TRAX:hello "trax.name=" "trax.family=" "trax.image=path;" "trax.region=rectangle;" "trax.description=" "trax.version=2" "trax.channels=color;ir;" 
CLIENT: Tracker process ID: 8987
CLIENT: Connection with tracker established.
@@TRAX:initialize "file:///home/adlu/vot-toolkit-master/sequences/baketballwaliking/color/00001v.jpg" "file:///home/adlu/vot-toolkit-master/sequences/baketballwaliking/ir/00001i.jpg" "374.0000,169.0000,20.0000,58.0000" 
@@TRAX:state "374.0000,169.0000,20.0000,58.0000" 
@@TRAX:frame "file:///home/adlu/vot-toolkit-master/sequences/baketballwaliking/color/00002v.jpg" "file:///home/adlu/vot-toolkit-master/sequences/baketballwaliking/ir/00002i.jpg" 
/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py:479: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dtype(int).type`.
  if issubdtype(ts, int):
/usr/lib/python2.7/dist-packages/scipy/misc/pilutil.py:482: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  elif issubdtype(type(size), float):
CLIENT: Trying to stop process using protocol.
@@TRAX:quit 
CLIENT: Trying to terminate process nicely.
CLIENT: Flushing streams
CLIENT: Process should be terminated.
CLIENT: Stopping logger.
CLIENT: Tracker exited (stopped by signal 15)
CLIENT: Trying to stop process using protocol.
CLIENT: Cleaning up.
CLIENT: Stopping logger thread
CLIENT: Trying to stop process using protocol.
      Tracker execution interrupted: Did not receive response.
错误使用 traxclient
Did not receive response.

出错 tracker_run (line 78)
    data = traxclient(tracker.command, callback, ...

出错 experiment_supervised (line 72)
    data = tracker_run(tracker, @callback, data);

出错 tracker_evaluate (line 57)
	[files, metadata] = experiment_function(tracker, sequence, directory, parameters, scan);

出错 workspace_evaluate>execute_iterator (line 128)
            tracker_evaluate(event.tracker, event.sequence, event.experiment);

出错 iterate (line 65)
            context = iterator(event, context);

出错 workspace_evaluate (line 93)
context = iterate(experiments, trackers, sequences, 'iterator', iterator, 'context', context);

出错 run_experiments (line 10)
workspace_evaluate(tracker, sequences, experiments);

**Comment by lukacu** [comment]
We have tested a very similar setup and found no problem.You can also try updating the toolkit to 7.0.2 if that helps.

**Comment by Alexadlu** [comment]
Thank you for your reply. I want to ask whether the current vot-toolkit does not support the version of pytorch>0.3
