### ISSUE TITLE
Octave: winsock library not linked when building native components

### ISSUE THREAD

**Issue by torazem** [votchallenge/toolkit-legacy#243]
During the "_Verifying native components ..._" step while running `workspace_create` or `run_test`,  I get the error: `undefined reference to __imp_WSACleanup` from `vot-toolkit\native\trax\src\message.c`.

After some searching, I borrowed from the solution to [this issue](https://github.com/open62541/open62541/issues/1734) and changed `vot-toolkit\utilities\compile_mex.m` (around line 45) from

```
    if is_octave()
        arguments{end+1} = '-DOCTAVE';
    else
        arguments{end+1} = '-lut';
    end
```
to
```
    if is_octave()
        arguments{end+1} = '-DOCTAVE';
        arguments{end+1} = '-lws2_32';
    else
        arguments{end+1} = '-lut';
    end
```

and it worked for me.

Could this be included in the toolkit?

**System**
Windows 10
Octave v5.1.0 configured for x86_64-w64-ming32
VOT toolkit 7.0.2
Trax 2.0.1

**Comment by lukacu** [comment]
Interesting, I will try to add this, but it is likely only applicable to Windows, so some additional checks will be required.
