### ISSUE TITLE
Passed in Matlab tracker but failed in Python tracker on Windows

### ISSUE THREAD

**Issue by Singapore-mor** [votchallenge/toolkit-legacy#249]
I successfully integrated tracker written in MATLAB,
tracker_label = 'NCC';
tracker_command = generate_matlab_command('ncc.', {'vot-toolkit-master/tracker/examples/matlab/'});
tracker_interpreter = 'matlab';

after that, I tested integrating tracker written in python and failed.It's always stays in 'testing TraX protocol support for tracker ncc',and it no result. 
tracker_label = ['NCC'];
tracker_command = generate_python_command('python_ncc', {'H:\dataset\vot-toolkit-python\vot-toolkit-master\tracker\examples\python\'});
tracker_interpreter = 'python';

Later I saw some solutions in website, and changed the code
tracker_label = ['NCC'];
tracker_command = generate_python_command('python_ncc', {'H:\dataset\vot-toolkit-python\vot-toolkit-master\tracker\examples\python\','H:\dataset\vot-toolkit-python\vot-toolkit-master\native\trax\support\python\'});
tracker_interpreter = 'python';
tracker_linkpath = {'H:\dataset\vot-toolkit-python\vot-toolkit-master\native\trax\build\'};

After that the results also remain the same... And I find some solutions use the libtrax.so, while I can't get it on windows...

I don't know how to solve the problems...anyone encounter this problem?Must I use it in on Ubuntu?

**Comment by mellthebs** [comment]
Me too! I found Trax won't generate 'build' after compile in windows.
