### ISSUE TITLE
vot2019 unable to establish connection

### ISSUE THREAD

**Issue by zhu2014yi** [votchallenge/toolkit-legacy#255]
hi. when  I try to use the ncc to run the vot2019, I got  unable to establish connection. 
the log is above ,
Is there some information or solution for this problem?

MATLAB is selecting SOFTWARE OPENGL rendering.

                            < M A T L A B (R) >
                  Copyright 1984-2017 The MathWorks, Inc.
                   R2017a (9.2.0.538062) 64-bit (glnxa64)
                             February 23, 2017

 
To get started, type one of these: helpwin, helpdesk, or demo.
For product information, visit www.mathworks.com.
 
@@TRAX:hello "trax.image=path;" "trax.region=rectangle;" "trax.version=3" "trax.channels=color;" 
@@TRAX:initialize "file:///ssd/VOT2019/agility/00000001.jpg" "550.2800,249.7100,22.4399,55.5300" 

image =

    '/ssd/VOT2019/agility/00000001.jpg'

@@TRAX:state "550.2800,249.7100,22.4399,55.5300" 
@@TRAX:frame "file:///ssd/VOT2019/agility/00000002.jpg" 

image =

    '/ssd/VOT2019/agility/00000002.jpg'

@@TRAX:state "569.0000,248.0000,23.0000,55.0000" "confidence=0.633273" 
@@TRAX:frame "file:///ssd/VOT2019/agility/00000003.jpg" 

image =

    '/ssd/VOT2019/agility/00000003.jpg'

@@TRAX:state "589.0000,246.0000,23.0000,55.0000" "confidence=0.638505" 
@@TRAX:quit "trax.reason=" 
MATLAB is selecting SOFTWARE OPENGL rendering.

![image](https://user-images.githubusercontent.com/42707205/79568386-554b7d00-80e8-11ea-930e-ae5c0b62bd49.png)

**Comment by lukacu** [comment]
Well, it looks like there was some initial communication, but after a few frames, something happened. It is not clear if it was a timeout or something else. I assume that you have Matlab tracker on Windows, those are very difficult to debug. These should be another file next to the log that may provide more information.
