### ISSUE TITLE
TypeError: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by Alexadlu** [votchallenge/toolkit-legacy#256]
colorimage_file, irimage_file = handle.frame()
TypeError: cannot unpack non-iterable NoneType object

During the test, there was an interruption and we couldn't figure out what caused it.I hope you can help me out.
It should be noted that more than 20 sequences can be tested, but the above problems have occurred. I am very confused, looking forward to your reply!

**Comment by lukacu** [comment]
Please first check if you are posting to the right repository, it is not clear if this deals with the new or the old toolkit. Also, specify which sequence you are having problem with.

**Comment by Alexadlu** [comment]
The problem currently located should be the restart mechanism. When the tracking fails and restarts, the handle.frame () here cannot obtain the image path, so there is an interruption. It is not clear how to solve this problem.

**Comment by Alexadlu** [comment]
VOT-Toolkit-matlab  
rgbtir-2019
matlab2016a 
tracker based on python

**Comment by lukacu** [comment]
This is strange. So if I understand correctly the tracker runs on some sequences and not on others? Or does this happen at the first restart?

**Comment by Alexadlu** [comment]
Yes, it's very strange, it's not that the first reboot will crash, it's that a reboot in some sequence will fail, it's not a certain sequence or a certain restart.
When I change the timeout = 300000000000000000000000000 (or other larger value ) can pass some sequence of the defeat of the restart, but behind still exists in some sequence of such failure, namely collapse when restart, then I modify the timeout has no effect

**Comment by lukacu** [comment]
The restart mechanism is very simple. A process is terminated and a new one is created. This is the cleanest way for the challenges, although the protocol supports a less drastic one.

I must say that I have no idea how to reproduce or debug this. We are currently directing all our efforts to the Python toolkit so you may want to try using that and see if you still have a problem. Not all previous challenges are fully supported in terms of analysis but at least you should be able to run the experiments.
