### ISSUE TITLE
VOT has an error in running the document

### ISSUE THREAD

**Issue by tianlewangzhe** [votchallenge/toolkit-legacy#259]
>> run_test
Initializing workspace ...
Checking for toolkit updates on GitHub.
Verifying native components ...
Loading sequences ...
错误使用 json_decode/error_pos (line 196)
Outer level structure must be an object or an array : ... F<error> ...

出错 json_decode (line 29)
            error_pos('Outer level structure must be an object or an array');

出错 sequence_load (line 52)
        meta = json_decode(fileread(listing));

**Comment by tianlewangzhe** [comment]
请问这个该如何解决

**Comment by bigonestep** [comment]
me too.
![Screenshot_20200808_074830](https://user-images.githubusercontent.com/23466526/89663889-dd0ffe00-d908-11ea-8c81-91f4227a2053.png)

**Comment by bigonestep** [comment]
I realized that the download might have failed, so I manually downloaded the data and copied it to the sequences folder, but I still reported an error. What is the format of the downloaded data set into the folder?
|--sequences
|----VOT2018
|------annotions
|--------ants1
|----------camera_motion.tag
|----------groundtruth.txt
|---------- ......(6)
|------ants1
|--------00000001jpg
|-------- .....
|------ants3
|------ ......

**Comment by tianlewangzhe** [comment]
I haven't solved it yet. Did you solve it? I also tried to download the dataset directly. However, it still has errors.

> I realized that the download might have failed, so I manually downloaded the data and copied it to the sequences folder, but I still reported an error. What is the format of the downloaded data set into the folder?
> |--sequences
> |----VOT2018
> |------annotions
> |--------ants1
> |----------camera_motion.tag
> |----------groundtruth.txt
> |---------- ......(6)
> |------ants1
> |--------00000001jpg
> |-------- .....
> |------ants3
> |------ ......

I haven't solved it yet. Did you solve it? I also tried to download the dataset directly. However, it still has errors.

**Comment by bigonestep** [comment]
@tianlewangzhe I haven't solved it yet.

**Comment by lukacu** [comment]
The error in JSON decoding means that the dataset manifest was probably not downloaded correctly. You can find its URL in the stack file and check if you can download it manually. I can do it on my machine, it looks ok.

Also please communicate in English if you expect help from the VOT team.

**Comment by tianlewangzhe** [comment]
Thank you very much for the author's tips. I added it manually and it worked well. When using the run_test file for testing, it can proceed smoothly. However, when running with the run_experiments file, an error occurred in the system. I checked the code inside and said it was more than 30 seconds before an error occurred. So, I changed it to 300,000. However, it just stopped there, without reflecting.

![image](https://user-images.githubusercontent.com/56470984/90332220-c004ba80-dfed-11ea-85ba-8b478ca94da7.png)

**Comment by tianlewangzhe** [comment]
This is strange. The first few sequences can run smoothly.

**Comment by tianlewangzhe** [comment]
It's really strange, an error suddenly appeared.
![image](https://user-images.githubusercontent.com/56470984/90403235-3cbd9480-e0d3-11ea-8a5b-ce6a44e519f3.png)
![image](https://user-images.githubusercontent.com/56470984/90403261-48a95680-e0d3-11ea-84b4-206543b0b284.png)
![Uploading image.png…]

**Comment by bigonestep** [comment]
@tianlewangzhe  Hello, how did you solve it in the end? Can I add WeChat to ask you for advice?

**Comment by tianlewangzhe** [comment]
> > Thank you very much for the author's tips. I added it manually and it worked well. When using the run_test file for testing, it can proceed smoothly. However, when running with the run_experiments file, an error occurred in the system. I checked the code inside and said it was more than 30 seconds before an error occurred. So, I changed it to 300,000. However, it just stopped there, without reflecting.
> > ![image](https://user-images.githubusercontent.com/56470984/90332220-c004ba80-dfed-11ea-85ba-8b478ca94da7.png)
> 
> Hi @tianlewangzhe, did you make any other change after downloading the dataset manually and copying them to the 'sequences' folder?
Yes, but there must be a data list in the "sequences" file directory.

**Comment by tianlewangzhe** [comment]
> @tianlewangzhe Hello, how did you solve it in the end? Can I add WeChat to ask you for advice?

I downloaded the dataset manually. Then, I put the data in the "sequences" file. It can pass and run normally. My qq: 2946767312

**Comment by gd1925** [comment]
Hi @tianlewangzhe,

Thank you for your reply. That solved my problem.

**Comment by lukacu** [comment]
Perhaps this is a network problem then, from which countries do you download sequences? I am trying to see a pattern here.

**Comment by tianlewangzhe** [comment]
> Perhaps this is a network problem then, from which countries do you download sequences? I am trying to see a pattern here.

I am in Changsha, Hunan, China. It is still not available for downloading, only manual downloading.
